name: Update Frontend Code

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-update-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend/
            infrastructure/
            modules/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Set Production API Base URL
        run: echo "VITE_API_BASE_URL=/api" > .env.production
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get CloudFront Distribution ID
        id: tf_output
        working-directory: infrastructure
        run: |
          terraform init
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT

      - name: Update S3 Bucket
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.tf_output.outputs.cloudfront_distribution_id }} \
            --paths "/*"